name: "prometheus-grafana"
type: static
path: "./manifests"
subcomponents:
  - name: "grafana"
    type: helm
    source: "https://grafana.github.io/helm-charts"
    method: "helm"
    path: "grafana"
  - name: "prometheus"
    type: helm
    source: "https://prometheus-community.github.io/helm-charts"
    method: "helm"
    path: "prometheus"
